### PR TITLE
Feature developer

### PR DESCRIPTION
**Pull request by kalavhan**

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :red_circle: Changes Required :red_circle: 
___
Hi @kalavhan :wave: ,
Great initiative. Really, all the part that is needed to decorate the page is in here :clap: :open_hands: . All you need to do is fix their view. And that is actually blocking me to approve this project. I am definitely sure that you will nail it.
___
##### Please Follow the instructions below to complete the project.
___
### :space_invader: Mandatory Changes :space_invader: 
___
#### :desktop_computer: Large window
1. Some items are overflowing the window. You can identify the issue by inspecting it on your browser. The opinion part is also collapsing with subscribe.
newstask1
___
 #### :iphone:  Medium window
1. The logo on the navbar is not horizontally centered. May be margin top can fix it.
newstask2
2. The subscribe and newsletter section appears one after another on the actual webpage. Well you have done a great job. So why should it be left.
---> Your One
newstask3
--->Actual One
actualtask3
___
 #### :iphone:  Small window
1. The navbar is broken. Both before scroll and after scroll.
---> Before Scroll
beforescroll
---> After Scroll
afterscroll
___
___
### :o: Optional Changes :o: 
___
1. the footer links are containing too much space. Well it feel that to me. May be a decreasing the padding will make it more attractive. On your list-group-item class, instead of padding: 0.75rem 1.25rem;  this padding: 0.25rem 0.75rem; could be used.
___
##### Please fix the above mentioned issue and send another review request. :pray: 
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)| [Slack](Shakhawat Hossain)

**Comment by kalavhan** [comment]
Fixed issues

**Review by Forison — COMMENTED** [review]
#### Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi @kalavhan🙂 
Good Job on implementing the changes suggested earlier.
Here are a few tweaks we have to do on the project implementation to have this project approved.
* [x] Let us get rid of the Horizontal scroll on the page. This could be due to bootstrap ```.col``` ```.container```  and ```.row``` conflicting🙂.
* [x] Let us improve the footer at SM  and MD media screen🙂. it does look too good. Let us take a clue from the original [page](newsweek.com)
* [x] let us use the bootstrap reference in the header instead of having the whole bootstrap stylesheet in the project. Let's use this in the header
 ```<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">```
## Kindly make these changes and submit the project for review🙂
#### Happy coding🙂

**Comment by kalavhan** [comment]
all changes have been applied

**Comment by shshamim63** [comment]
## Status :musical_score:  <em>!!! Approved !!!</em>
___
Hi @kalavhan :wave: ,
Great job :clap: . I can see all the part that is needed to declare this project as complete. In one line`You have cracked this achievement`.
___
#### This :+1: is from me. You can merge it and don't forget to submit the project completion form. Best of luck for your new project.
___  
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)| [Slack](Shakhawat Hossain)

**Pull request merged**
